### ISSUE TITLE
Broken link.

### ISSUE THREAD

**Issue by jishindev** [LouisCAD/solution.bike#1]
Hey Louis. The link www.solution.bike seems to be broken.

**Comment by LouisCAD** [comment]
Hey, yes, as you can see, the website is not done yet. This will be fixed
when I figure out how to make it work and have time enough to make it. FYI,
it'll be hosted on Firebase.

**Comment by jishindev** [comment]
I see. Clicked on the link without checking the repo out fully. My bad. 
Firebase Hosting allows code other than static content too? Didn't know. Will check that out.

**Comment by LouisCAD** [comment]
I should add a WIP page that redirects to the repo or an issue like
"Publish the website"

**Comment by jishindev** [comment]
WIP page would be better IMO. 
Firebase Hosting only allows HTML, CSS and JS right? Correct me if I'm wrong. A serverless architecture can be achieved by using the Cloud functions but thats done with node.js I believe. 
In that case I'm guessing this project is a static website built using Kotlin/JS.

**Comment by LouisCAD** [comment]
Firebasz hosting is just to host static files, which include html, css and
js, yes. But those files can be generated from Kotlin (anything really).
Firebase Functions can also complement it, and can be written with
Kotlin/JS source too.
